steps:

  # Build Docker image for client
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-client'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        docker build -f client/Dockerfile.dev -t $${ARTIFACTS}/client-img-$${ENV}:${SHORT_SHA} client \
        --build-arg AUTH0_CLIENT_SECRET=$${AUTH0_CLIENT_SECRET} \
        --build-arg REACT_APP_API_1_URL=$${REACT_APP_API_1_URL} \
        --build-arg REACT_APP_API_2_URL=$${REACT_APP_API_2_URL} \
        --build-arg REACT_APP_AUTH0_AUDIENCE=$${ROOT_URL} \
        --build-arg REACT_APP_AUTH0_CLIENT_ID=$${AUTH0_CLIENT_ID} \
        --build-arg REACT_APP_AUTH0_URL=$${AUTH0_URL} \
        --build-arg REACT_APP_PUBLIC_STRIPE_KEY=$${PUBLIC_STRIPE_KEY} \
        --build-arg REACT_APP_ROOT_URL=$${ROOT_URL} \
    secretEnv:
      - 'ARTIFACTS'
      - 'AUTH0_CLIENT_ID'
      - 'AUTH0_CLIENT_SECRET'
      - 'AUTH0_URL'
      - 'ENV'
      - 'PUBLIC_STRIPE_KEY'
      - 'REACT_APP_API_1_URL'
      - 'REACT_APP_API_2_URL'
      - 'ROOT_URL'

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-client'
    entrypoint: 'bash'
    args: ['-c', 'docker push $${ARTIFACTS}/client-img-$${ENV}:${SHORT_SHA}']
    secretEnv:
      - 'ARTIFACTS'
      - 'ENV'

  # Tag client as new revision and deploy to Cloud Run without traffic
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-client'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy wtix-client-$${ENV} \
        --image $${ARTIFACTS}/client-img-$${ENV}:${SHORT_SHA} \
        --revision-suffix=${SHORT_SHA} \
        --region $${REGION} \
        --platform managed \
        --memory $${CLIENT_MEMORY} \
        --cpu $${CLIENT_CPU} \
        --cpu-boost \
        --allow-unauthenticated \
        --min-instances 1 \
        --max-instances 10 \
        --no-traffic \
        --tag new \
        --service-account $${SERVICE_ACCOUNT} \
        --set-env-vars=\
        ENV=$${ENV}, \
        --set-secrets=\
        REACT_APP_AUTH0_CLIENT_ID=AUTH0_CLIENT_ID:$${ENV},\
        REACT_APP_PUBLIC_STRIPE_KEY=PUBLIC_STRIPE_KEY:$${ENV}
    secretEnv:
      - 'ARTIFACTS'
      - 'CLIENT_CPU'
      - 'CLIENT_MEMORY'
      - 'ENV'
      - 'REGION'
      - 'SERVICE_ACCOUNT'

  # Request page from new revision and wait for container to start
  - name: 'mcr.microsoft.com/playwright:latest'
    id: 'wake-client'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install playwright
        export NODE_PATH=$$(pwd)/node_modules
        node client/wake-client.js $${NEW_REVISION}
    secretEnv:
      - 'ENV'
      - 'NEW_REVISION'

  # Gradually send traffic to new revision, then remove `new` tag
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'send-traffic'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        function update_traffic() {
          local PERCENTAGE=$${1}
          echo "Sending $${PERCENTAGE}% of traffic to new revision..."
          gcloud run services update-traffic wtix-client-$${ENV} \
          --region $${REGION} \
          --to-revisions=wtix-client-$${ENV}-${SHORT_SHA}=$${PERCENTAGE}
        }

        update_traffic 5 && sleep 30
        update_traffic 25 && sleep 30
        update_traffic 50 && sleep 30
        update_traffic 100 && sleep 30

        gcloud run services update-traffic wtix-client-$${ENV} \
        --region $${REGION} \
        --remove-tags new
    secretEnv:
      - 'ENV'
      - 'REGION'

# Use dev, stg, or prd versions depending on $_ENV value from trigger
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/ARTIFACTS/versions/${_ENV}
    env: 'ARTIFACTS'
  - versionName: projects/${PROJECT_ID}/secrets/AUTH0_CLIENT_ID/versions/${_ENV}
    env: 'AUTH0_CLIENT_ID'
  - versionName: projects/${PROJECT_ID}/secrets/AUTH0_CLIENT_SECRET/versions/${_ENV}
    env: 'AUTH0_CLIENT_SECRET'
  - versionName: projects/${PROJECT_ID}/secrets/AUTH0_URL/versions/${_ENV}
    env: 'AUTH0_URL'
  - versionName: projects/${PROJECT_ID}/secrets/CLIENT_CPU/versions/${_ENV}
    env: 'CLIENT_CPU'
  - versionName: projects/${PROJECT_ID}/secrets/CLIENT_MEMORY/versions/${_ENV}
    env: 'CLIENT_MEMORY'
  - versionName: projects/${PROJECT_ID}/secrets/ENV/versions/${_ENV}
    env: 'ENV'
  - versionName: projects/${PROJECT_ID}/secrets/NEW_REVISION/versions/${_ENV}
    env: 'NEW_REVISION'
  - versionName: projects/${PROJECT_ID}/secrets/PUBLIC_STRIPE_KEY/versions/${_ENV}
    env: 'PUBLIC_STRIPE_KEY'
  - versionName: projects/${PROJECT_ID}/secrets/REACT_APP_API_1_URL/versions/${_ENV}
    env: 'REACT_APP_API_1_URL'
  - versionName: projects/${PROJECT_ID}/secrets/REACT_APP_API_2_URL/versions/${_ENV}
    env: 'REACT_APP_API_2_URL'
  - versionName: projects/${PROJECT_ID}/secrets/REGION/versions/${_ENV}
    env: 'REGION'
  - versionName: projects/${PROJECT_ID}/secrets/ROOT_URL/versions/${_ENV}
    env: 'ROOT_URL'
  - versionName: projects/${PROJECT_ID}/secrets/SERVICE_ACCOUNT/versions/${_ENV}
    env: 'SERVICE_ACCOUNT'
  - versionName: projects/$PROJECT_ID/secrets/SQL_INSTANCE/versions/$_ENV
    env: 'SQL_INSTANCE'
