steps:

  # Build the Docker image for the client
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'REACT_APP_ROOT_URL=https://wondertix-server-s2jfqf45ha-wl.a.run.app'
      - 'REACT_APP_AUTH0_URL=https://wtix-dev.us.auth0.com'
      - 'REACT_APP_AUTH0_AUDIENCE=https://wondertix-server-s2jfqf45ha-wl.a.run.app'
      - 'REACT_APP_API_1_URL=https://wondertix-server-s2jfqf45ha-wl.a.run.app/1'
      - 'REACT_APP_API_2_URL=https://wondertix-server-s2jfqf45ha-wl.a.run.app/2'
      - 'ENV=dev'
    args: ['build', '-f', 'client/Dockerfile.dev', '-t', 'us-west2-docker.pkg.dev/wondertix-394321/wondertix-cd-test-artifact-registry-repository/wondertix-client', 'client']

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west2-docker.pkg.dev/wondertix-394321/wondertix-cd-test-artifact-registry-repository/wondertix-client']

  # Deploy the client image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'REACT_APP_ROOT_URL=https://wondertix-server-s2jfqf45ha-wl.a.run.app'
      - 'REACT_APP_AUTH0_URL=https://wtix-dev.us.auth0.com'
      - 'REACT_APP_AUTH0_AUDIENCE=https://wondertix-server-s2jfqf45ha-wl.a.run.app'
      - 'REACT_APP_API_1_URL=https://wondertix-server-s2jfqf45ha-wl.a.run.app/1'
      - 'REACT_APP_API_2_URL=https://wondertix-server-s2jfqf45ha-wl.a.run.app/2'
      - 'ENV=dev'
    args:
      - 'run'
      - 'deploy'
      - 'wondertix-client'
      - '--image'
      - 'us-west2-docker.pkg.dev/wondertix-394321/wondertix-cd-test-artifact-registry-repository/wondertix-client'
      - '--region'
      - 'us-west2'
      - '--platform'
      - 'managed'
