# Build stage
FROM node:18-alpine as builder
WORKDIR /usr/app
COPY ./package*.json ./
RUN npm install --production

# Production stage
FROM node:18-alpine
WORKDIR /usr/app
COPY --from=builder /usr/app/node_modules ./node_modules

# Copy only files needed to run
COPY . .
