###

POST http://localhost:8000/api/saved_reports HTTP/1.1
content-type: application/json

{
    "table_name": "Test Query 2",
    "query_attr": "donations/?filters[donodate][$gt]=2022-01-01"
}

###

GET http://localhost:8000/api/saved_reports
###