import React from 'react';
import {DataGrid} from '@mui/x-data-grid';

const compColumns = [
  {field: 'event', headerName: 'Event', flex: 2.5},
  {field: 'instance', headerName: 'Instance', flex: 4},
  {field: 'refund', headerName: 'Allocation', flex: 1.5},
  {field: 'pricelevel', headerName: 'Price Level', flex: 1.5},
  {field: 'quantity', headerName: 'Quantity', flex: 1},
  {field: 'price', headerName: 'Price', flex: 1},
  {field: 'Fee', headerName: 'Fee', flex: 1},
  {field: 'Ticket', headerName: 'Ticket Fee', flex: 1},
  {field: 'Patron', headerName: 'Patron Fee', flex: 1},
  {field: 'nto', headerName: 'Net to Org', flex: 1},
];

const compRows = [
  {
    id: 0,
    event: 'Sold Items',
    quantity: '-15',
    price: '-525.00',
    Fee: '-30.00',
    Ticket: '0.00',
    Patron: '14.40',
    nto: '-540.60',
  },
  {
    id: 1,
    event: 'Chicken & Biscuits',
    quantity: '-2',
    price: '-50.00',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '1.70',
    nto: '-48.30',
  },
  {
    id: 2,
    event: '',
    instance: 'Saturday, Oct 29 at 7:30pm',
    refund: 'Access Tickets',
    pricelevel: 'Access',
    quantity: '-2',
    price: '-50.00',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '1.70',
    nto: '-48.30',
  },
  {
    id: 3,
    event: 'The Sounds of Afrolitical Movement',
    quantity: '-13',
    price: '-475.00',
    Fee: '-30.00',
    Ticket: '0.00',
    Patron: '12.70',
    nto: '-492.30',
  },
  {
    id: 4,
    event: '',
    instance: 'Sunday, May 28 at 2:00pm - One Second Line at a time',
    refund: 'General Admission',
    pricelevel: 'Adult',
    quantity: '-2',
    price: '-79.00',
    Fee: '-6.00',
    Ticket: '0.00',
    Patron: '2.00',
    nto: '-83.00',
  },
  {
    id: 5,
    event: '',
    instance: 'Thursday, June 1 at 7:30pm - Baptism & Rebirth',
    refund: 'General Admission',
    pricelevel: 'Adult',
    quantity: '-1',
    price: '-39.50',
    Fee: '-3.00',
    Ticket: '0.00',
    Patron: '1.00',
    nto: '-41.50',
  },
  {
    id: 6,
    event: '',
    instance: 'Thursday, June 8 at 7:30pm - Baptism & Rebirth',
    refund: 'General Admission',
    pricelevel: 'Adult',
    quantity: '-5',
    price: '-179.50',
    Fee: '-15.00',
    Ticket: '0.00',
    Patron: '5.00',
    nto: '-207.50',
  },
  {
    id: 7,
    event: '',
    instance: 'Friday, June 9 at 7:30pm - A Meditation on Stillness',
    refund: 'General Admission',
    pricelevel: 'Adult',
    quantity: '-2',
    price: '-40.00',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '1.70',
    nto: '-38.30',
  },
  {
    id: 8,
    event: '',
    instance: 'Wednesday, June 14 at 7:30pm - Chaos',
    refund: 'General Admission',
    pricelevel: 'Adult',
    quantity: '-2',
    price: '-79.00',
    Fee: '-6.00',
    Ticket: '0.00',
    Patron: '2.00',
    nto: '-83.00',
  },
  {
    id: 9,
    event: '',
    instance: 'Thursday, June 15 at 7:30pm - Baptism & Rebirth',
    refund: 'General Admission',
    pricelevel: 'Adult',
    quantity: '-1',
    price: '-40.00',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '1.00',
    nto: '-39.00',
  },
  {
    id: 10,
    event: 'Subscription Exchange',
    quantity: '0',
    price: '-3,375.00',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '0.00',
    nto: '-3,375.00',
  },
  {
    id: 11,
    event: 'Season 15 Vouchers',
    quantity: '0',
    price: '-1,945.00',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '0.00',
    nto: '-1,945.00',
  },
  {
    id: 12,
    instance: '3 Show Vouchers',
    quantity: '0',
    price: '-587.00',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '0.00',
    nto: '-587.00',
  },
  {
    id: 13,
    refund: 'Anytime',
    quantity: '0',
    price: '-513.00',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '0.00',
    nto: '-513.00',
  },
  {
    id: 14,
    pricelevel: 'Show 2 (Adult)',
    quantity: '0',
    price: '-232.02',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '0.00',
    nto: '-232.02',
  },
  {
    id: 15,
    pricelevel: 'Show 3 (Adult)',
    quantity: '0',
    price: '-148.98',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '0.00',
    nto: '-148.98',
  },
  {
    id: 16,
    pricelevel: 'Show 3 (Flash Sale)',
    quantity: '0',
    price: '-132.00',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '0.00',
    nto: '-132.00',
  },
  {
    id: 17,
    refund: 'Sometimes',
    quantity: '0',
    price: '-74.00',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '0.00',
    nto: '-74.00',
  },
  {
    id: 18,
    pricelevel: 'Show 3 (Adult)',
    quantity: '0',
    price: '-74.00',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '0.00',
    nto: '-74.00',
  },
  {
    id: 19,
    instance: '3 Show Vouchers',
    quantity: '0',
    price: '-587.00',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '0.00',
    nto: '-587.00',
  },
  {
    id: 20,
    refund: 'Anytime',
    quantity: '0',
    price: '-1,284.00',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '0.00',
    nto: '-1,284.00',
  },
  {
    id: 21,
    pricelevel: 'Show 2 (Adult)',
    quantity: '0',
    price: '-99.50',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '0.00',
    nto: '-99.50',
  },
  {
    id: 22,
    pricelevel: 'Show 3 (Adult)',
    quantity: '0',
    price: '-248.75',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '0.00',
    nto: '-248.75',
  },
  {
    id: 23,
    pricelevel: 'Show 3 (Under 25)',
    quantity: '0',
    price: '-90.00',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '0.00',
    nto: '-90.00',
  },
  {
    id: 24,
    pricelevel: 'Show 4 (Adult)',
    quantity: '0',
    price: '-845.75',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '0.00',
    nto: '-845.75',
  },
  {
    id: 25,
    refund: 'Sometimes',
    quantity: '0',
    price: '-74.00',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '0.00',
    nto: '-74.00',
  },
  {
    id: 26,
    pricelevel: 'Show 3 (Adult)',
    quantity: '0',
    price: '-74.00',
    Fee: '0.00',
    Ticket: '0.00',
    Patron: '0.00',
    nto: '-74.00',
  },
];

const ExchangeSalesPriceLevelReport = (): React.ReactElement => {
  const rowHeight = 36;
  const compTableRows = compRows.length;
  const tableHeight = ((compTableRows * rowHeight) + rowHeight + 5);

  return (
    <div className='h-fit w-auto p-2 mt-4'>
      <h1 className='text-2xl font-bold p-2 my-2'>
        Refund & Exchange Totals
        <span className='text-xl font-medium'>
          {' (Price Level Details)'}
        </span>
      </h1>

      <div className='bg-slate-50'>
        <h2 className='text-lg font-bold p-2 border'>Refunded/Exchanged:</h2>
        <DataGrid
          hideFooter
          rows={compRows}
          columns={compColumns}
          disableSelectionOnClick
          density="compact"
          style={{height: `${tableHeight}px`, fontSize: '0.8rem', borderRadius: 0}}
        />
      </div>
    </div>
  );
};

export default ExchangeSalesPriceLevelReport;
