steps:

  # Build server image using Dockerfile.dev
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build -f server/Dockerfile.dev -t $$ARTIFACTS/server-img-$$ENV server']
    secretEnv: ['ARTIFACTS', 'ENV']

  # Push image to artifact registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker push $$ARTIFACTS/server-img-$$ENV']
    secretEnv: ['ARTIFACTS', 'ENV']

  # Deploy image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy wtix-server-$$ENV \
        --image $$ARTIFACTS/server-img-$$ENV \
        --region $$REGION \
        --platform managed \
        --memory 1Gi \
        --allow-unauthenticated \
        --min-instances 1 \
        --set-cloudsql-instances $$SQL_INSTANCE \
        --service-account $$SERVICE_ACCOUNT
    secretEnv:
      - 'ARTIFACTS'
      - 'AUTH0_AUDIENCE'
      - 'AUTH0_CLIENT_SECRET'
      - 'AUTH0_URL'
      - 'DATABASE_URL'
      - 'DB_DATABASE'
      - 'DB_HOST'
      - 'DB_PASSWORD'
      - 'DB_PORT'
      - 'DB_USER'
      - 'ENV'
      - 'FRONTEND_URL'
      - 'REGION'
      - 'ROOT_URL'
      - 'SERVICE_ACCOUNT'
      - 'SQL_INSTANCE'

# Use dev or stg versions depending on _ENV value from trigger
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/ARTIFACTS/versions/$_ENV
    env: 'ARTIFACTS'
  - versionName: projects/$PROJECT_ID/secrets/AUTH0_AUDIENCE/versions/$_ENV
    env: 'AUTH0_AUDIENCE'
  - versionName: projects/$PROJECT_ID/secrets/AUTH0_CLIENT_SECRET/versions/$_ENV
    env: 'AUTH0_CLIENT_SECRET'
  - versionName: projects/$PROJECT_ID/secrets/AUTH0_URL/versions/$_ENV
    env: 'AUTH0_URL'
  - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/$_ENV
    env: 'DATABASE_URL'
  - versionName: projects/$PROJECT_ID/secrets/DB_DATABASE/versions/$_ENV
    env: 'DB_DATABASE'
  - versionName: projects/$PROJECT_ID/secrets/DB_HOST/versions/$_ENV
    env: 'DB_HOST'
  - versionName: projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/$_ENV
    env: 'DB_PASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/DB_PORT/versions/$_ENV
    env: 'DB_PORT'
  - versionName: projects/$PROJECT_ID/secrets/DB_USER/versions/$_ENV
    env: 'DB_USER'
  - versionName: projects/$PROJECT_ID/secrets/ENV/versions/$_ENV
    env: 'ENV'
  - versionName: projects/$PROJECT_ID/secrets/FRONTEND_URL/versions/$_ENV
    env: 'FRONTEND_URL'
  - versionName: projects/$PROJECT_ID/secrets/REGION/versions/$_ENV
    env: 'REGION'
  - versionName: projects/$PROJECT_ID/secrets/ROOT_URL/versions/$_ENV
    env: 'ROOT_URL'
  - versionName: projects/$PROJECT_ID/secrets/SERVICE_ACCOUNT/versions/$_ENV
    env: 'SERVICE_ACCOUNT'
  - versionName: projects/$PROJECT_ID/secrets/SQL_INSTANCE/versions/$_ENV
    env: 'SQL_INSTANCE'

