import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://localhost:3000/');
  await page.getByRole('button', { name: 'See Showings' }).first().click();
  await page.getByRole('combobox').first().selectOption('Wed Sep 15 2021 03:00:00 GMT-0700 (Pacific Daylight Time)');
  await page.getByText('Ticket Type', { exact: true }).click();
  await page.getByText('Ticket Type', { exact: true }).click();
  await page.getByRole('combobox').first().selectOption('372');
  await page.locator('div').filter({ hasText: /^Ticket Typeselect ticket typeGeneral Admission - Adult: \$20\.00$/ }).getByRole('combobox').selectOption('General Admission - Adult');
  await page.locator('div').filter({ hasText: /^Quantityselect qty1234567891011121314151617181920$/ }).getByRole('combobox').selectOption('1');
  await page.getByRole('button', { name: 'Get Tickets' }).click();
  await page.getByRole('button', { name: 'Take me there!' }).click();
  await page.getByRole('button', { name: 'Proceed To Checkout' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByPlaceholder('First Name').click();
  await page.getByPlaceholder('First Name').fill('Sawyer');
  await page.getByPlaceholder('First Name').press('Tab');
  await page.getByPlaceholder('Last Name').fill('Norquist');
  await page.getByPlaceholder('Last Name').press('Tab');
  await page.getByPlaceholder('Street Address').fill('12345 Luggage Code Lane');
  await page.getByPlaceholder('Street Address').press('Tab');
  await page.getByPlaceholder('Postal Code').fill('86753');
  await page.getByPlaceholder('Postal Code').press('Tab');
  await page.getByPlaceholder('Country').fill('US');
  await page.getByPlaceholder('Country').press('Tab');
  await page.getByPlaceholder('Phone').fill('538675309');
  await page.getByPlaceholder('Phone').press('Tab');
  await page.getByPlaceholder('Email', { exact: true }).fill('snorq2@pdx.edu');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('Email').click();
  await page.getByLabel('Email').fill('snorq2@pdx.edu');
  await page.getByLabel('Email').press('Tab');
  await page.getByPlaceholder('1234 1234 1234 1234').fill('4242 4242 4242 42422');
  await page.getByPlaceholder('1234 1234 1234 1234').press('Tab');
  await page.getByPlaceholder('MM / YY').fill('12 / 34');
  await page.getByPlaceholder('MM / YY').press('Tab');
  await page.getByPlaceholder('CVC').fill('666');
  await page.getByPlaceholder('CVC').press('Tab');
  await page.getByPlaceholder('Full name on card').fill('Bob Placeholder');
  await page.getByPlaceholder('ZIP').click();
  await page.getByPlaceholder('ZIP').fill('99999');
  await page.getByTestId('hosted-payment-submit-button').click();
  await page.getByLabel('Save my info for 1-click checkout with LinkPay faster on this site and everywhere Link is accepted.').uncheck();
  await page.getByTestId('hosted-payment-submit-button').click();
  await page.getByRole('button', { name: 'Back to Home' }).click();
  await page.goto('https://localhost:3000/ticketing/doorlist');
  await page.getByLabel('Choose Event').selectOption('32');
  await page.getByLabel('Choose Time').selectOption('372');
  await page.getByLabel('Choose Time').selectOption('373');
  await page.getByLabel('Choose Time').selectOption('374');
  await page.getByLabel('Choose Time').selectOption('375');
  await page.getByLabel('Choose Time').selectOption('377');
  await page.getByLabel('Choose Time').selectOption('378');
  await page.getByLabel('Choose Time').selectOption('379');
  await page.getByLabel('Choose Time').selectOption('380');
  await page.getByLabel('Choose Time').selectOption('381');
  await page.getByLabel('Choose Time').selectOption('382');
  await page.goto('https://localhost:3000/');
  await page.locator('div').filter({ hasText: /^EventsPick an Event$/ }).first().click();
  await page.goto('https://localhost:3000/ticketing/doorlist');
  await page.getByLabel('Choose Event').selectOption('32');
  await page.getByLabel('Choose Time').selectOption('386');
  await page.getByLabel('Choose Time').selectOption('385');
  await page.getByLabel('Choose Time').selectOption('384');
  await page.getByLabel('Choose Event').selectOption('36');
  await page.getByLabel('Choose Time').selectOption('440');
});